# The following environmental variables need to be set in the Travis console
# AWS_DEFAULT_REGION=us-east-1
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=

language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt -t src/
  - pip install boto3

script: python deploy.py
